server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  google:
    auth:
      url: 'https://oauth2.googleapis.com'
      scope: 'profile,email,openid'
    login:
      url: 'https://accounts.google.com'
    redirect:
      url: 'http://localhost:8080/google/login/redirect'
    client:
      id: '969617440750-03gph3ivjcsd7pb5et3bsdm6sfuraroa.apps.googleusercontent.com'
    secret: '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'

  kakao:
    auth:
      url: 'https://kapi.kakao.com/v2/user/me'
    login:
      url: 'https://kauth.kakao.com'
    client:
      id: 'cf44fc6cf8011ba338bf7a941e9557e5'
    redirect:
      url: 'http://localhost:8080/kakao/login/callback'

  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/tripComesTrue
    driver-class-name: org.h2.Driver
    username: sa
    password: as

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

  output:
    ansi:
      enabled: always


jwt:
  secret: tripComesFalse

logging:
  level:
    '[org.springframework.boot.web]': DEBUG
    org:
      springframework:
        cache: DEBUG


